spring:
  application:
    name: exam-app
  profiles:
    active: local
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME}
    url: jdbc:mysql://${examapp.db.host}:${SPRING_DATASOURCE_PORT}/examappdb
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
server:
  port: 8081
jwt:
  secret-key: ${JWT_SECRET_KEY}
  expiration-time: 3600
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      table-prefix: "t_"
  mapper-locations: "classpath:/mapper/*.xml"
aws:
  credentials:
    accessKey: ${AWS_ACCESS_KEY}
    secretKey: ${AWS_SECRET_KEY}
  settings:
    similarityThreshold: 70.0