examapp:
  sql:
    username: root
    host: localhost
    password: root
    db: examappdb
  redis:
    port: 6379
    host: 192.168.91.129
    password: 123456
logging:
  level:
    root: info


