
spring:
  application:
    name: exam-app
  profiles:
    active: local
  datasource:
    username: ${SRPING_DATASOURCE_USERNAME}
    url: ${jdbc:mysql://examapp-mysql:3306/examappdb}
    password: ${SRPING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  data:
    redis:
      port: 6379
      password: 123456
      host: 127.0.0.1
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s
server:
  port: 8081
jwt:
  secret-key: ${JWT_SECRET_KEY}
  expiration-time: 3600
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      table-prefix: "t_"
  mapper-locations: "classpath:/mapper/*.xml"
aws:
  credentials:
    accessKey: ${AWS_ACCESS_KEY}
    secretKey: ${AWS_SECRET_KEY}
  settings:
    similarityThreshold: 70.0
